-- Step 06: POST /enrollments/enrollment/owner-entered
-- Downstream:
--   unite-profile → CloudOwnerService.verifyOwnerInfo() — domain validation (no DB on verify path)
--   unite-account → RootAccountService.postVerifyRootAccounts() — fraud + existing account check
-- Tables: TU_FRAUD_BLOCK_INFO, TU_PERSON, TU_ACCT

-- ---------------------------------------------------------------------------
-- 1) Owner SSN not fraud-blocked (must return 0 rows)
-- Source: FraudBlockInfoTableDao.findBySsn (SSN_H = hashed SSN)
-- ---------------------------------------------------------------------------
-- Note: SSN_H is a hash stored by the service; for test data use fresh unique SSNs
-- generated by EnrollmentTestDataBuilder instead of querying this table pre-run.
SELECT f.seq_fraud_block_info_id,
       f.ssn_h,
       f.permanent_flag
FROM tu_fraud_block_info f
WHERE f.ctl_rec_stat IN ('A', 'R')
  AND (f.permanent_flag = 'Y'
       OR (f.temp_block_flag = 'Y' AND f.temp_block_endtime > SYSDATE))
  AND f.ssn_h = :owner_ssn_hash;   -- hash computed by service; skip unless debugging

-- ---------------------------------------------------------------------------
-- 2) Check no existing root account for owner SSN on this plan
-- Source: RootAccountService — AccountTable by traunch_id + seq_part_id
-- ---------------------------------------------------------------------------
SELECT a.uii_acct_id,
       a.uii_acct_ext,
       a.traunch_id,
       p.seq_part_id
FROM tu_person p
INNER JOIN tu_acct a ON a.seq_part_id = p.seq_part_id
INNER JOIN tu_traunch t ON t.traunch_id = a.traunch_id
WHERE p.ctl_rec_stat = 'A'
  AND a.ctl_rec_stat = 'A'
  AND UPPER(t.branding) = UPPER('hawaii')
  AND p.ssn_h = :owner_ssn_hash;   -- bind if checking collision

-- ---------------------------------------------------------------------------
-- 3) Valid owner DOB range — no SQL; use ISO date e.g. 1985-03-15T05:00:00.000Z
-- Valid phone: 10 digits, phoneType = 'C' (cell) or 'H' (home)
