--SELECT TABLE_NAME, OWNER FROM ALL_TABLES WHERE LOWER(TABLE_NAME) LIKE 'qa%'; --ORDER BY owner, table_name;

CREATE TABLE QA_FIN_TXN (
  UII_ACCT_ID VARCHAR2(11) NOT NULL,
  SEQ_ACCT_ID NUMBER NOT NULL,
  TO_SEQ_ACCT_ID NUMBER NOT NULL,
  TRAUNCH_ID VARCHAR2(6) NOT NULL,
  TRANSACTION_TYPE VARCHAR2(25) NOT NULL,
  TRANSACTION_SUB_TYPE VARCHAR2(50),
  ORIGINAL_PRINCIPAL NUMBER NOT NULL,
  ORIGINAL_PRINCIPAL_TOACCT NUMBER,
  NEW_PRINCIPAL NUMBER,
  SEQ_QA_FIN_TXN_ID NUMBER NOT NULL,
  SEQ_FIN_TXN_ID NUMBER,
  LINKED_TXN_ID NUMBER,
  SEQ_PAY_ID NUMBER,
  MAX_CONTRIB_FLAG VARCHAR2(1),
  TEST_CASE_NAME VARCHAR2(255),
  CTL_INS_DTTM DATE,
 
  CONSTRAINT SEQ_QA_FIN_TXN_ID_PK PRIMARY KEY (SEQ_QA_FIN_TXN_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM QA_FIN_TXN FOR SPATIL.QA_FIN_TXN;
 
GRANT INSERT, SELECT, UPDATE ON QA_FIN_TXN TO PUBLIC; 
CREATE SEQUENCE SEQ_QA_FIN_TXN_PK START WITH 1;

---------------------------------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_QA_FIN_TXN BEFORE UPDATE OR INSERT ON QA_FIN_TXN FOR EACH ROW
        BEGIN
          IF INSERTING
          THEN
             :NEW.SEQ_QA_FIN_TXN_ID := SEQ_QA_FIN_TXN_PK.NEXTVAL;
          END IF;
 
          :NEW.CTL_INS_DTTM := SYSTIMESTAMP;
   EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (-30000,
                                  SQLERRM || TO_CHAR (SQLCODE, '09999'));
END TRG_QA_FIN_TXN;
/
------------------------------------------------------------------------------------------------------------------------------------------- 
 
CREATE TABLE QA_FIN_INSTRUCTION (
  SEQ_QA_FIN_INSTRUCTION_ID NUMBER,
  SEQ_QA_FIN_TXN_ID NUMBER NOT NULL,
  SEQ_NUM NUMBER,
  FUND_ID NUMBER,
  AMOUNT_TYPE VARCHAR2(10),
  AMOUNT NUMBER NOT NULL,
  PRINCIPAL_AMOUNT NUMBER,
  ACTIVITY VARCHAR2(3) NOT NULL,
  FIN_TYPE VARCHAR2(9) DEFAULT 'FUND',
  COMMENTS VARCHAR(50),
  CTL_INS_DTTM DATE,
 
  CONSTRAINT SEQ_QA_FIN_INSTR_ID_PK PRIMARY KEY (SEQ_QA_FIN_INSTRUCTION_ID),
  CONSTRAINT SEQ_QA_FIN_TXN_ID_FK FOREIGN KEY (SEQ_QA_FIN_TXN_ID) REFERENCES QA_FIN_TXN(SEQ_QA_FIN_TXN_ID)
);

CREATE OR REPLACE PUBLIC SYNONYM QA_FIN_INSTRUCTION FOR SPATIL.QA_FIN_INSTRUCTION;

GRANT INSERT, SELECT, UPDATE ON QA_FIN_INSTRUCTION TO PUBLIC; 
CREATE SEQUENCE SEQ_QA_FIN_INSTR_ID_PK START WITH 1;
 
CREATE OR REPLACE TRIGGER TRG_QA_FIN_INSTRUCTION BEFORE UPDATE OR INSERT ON QA_FIN_INSTRUCTION FOR EACH ROW
        BEGIN
          IF INSERTING
          THEN
             :NEW.SEQ_QA_FIN_INSTRUCTION_ID := SEQ_QA_FIN_INSTR_ID_PK.NEXTVAL;
          END IF;
 
          :NEW.CTL_INS_DTTM := SYSTIMESTAMP;
   EXCEPTION
      WHEN OTHERS
      THEN
         RAISE_APPLICATION_ERROR (-30000,
                                  SQLERRM || TO_CHAR (SQLCODE, '09999'));
END TRG_QA_FIN_INSTRUCTION;
/


--SELECT * FROM QA_FIN_TXN;
--SELECT * FROM QA_FIN_INSTRUCTION;

--SELECT * FROM tu_fin_txn WHERE UII_ACCT_ID = '91954456401';
COMMIT;
