apiVersion: v1
kind: Pod
metadata:
  name: perf-taurus-docker-pod-broker
  namespace: ags-qa
spec:
  restartPolicy: Never
  containers:
  - name: perf-taurus-docker-container-broker
    image: blazemeter/taurus:1.16.32
    command: ["/bin/sh"]
    args:
    - "-c"
    - "cp /bzt-configs-mount/TestRunBroker.yml /bzt-configs-mount/broker.jmx /bzt-configs-mount/broker.csv  /bzt-configs/; ls /bzt-configs; pwd; bzt TestRunBroker.yml broker.jmx"
    #- "cp /bzt-configs-mount/TestRunBroker.yml /bzt-configs-mount/broker.jmx /bzt-configs-mount/broker.csv /bzt-configs/; ls /bzt-configs; pwd; bzt -l /tmp/artifacts/bzt.log -report TestRunBroker.yml broker.jmx --option=execution.0.concurrency=2 --option=execution.0.hold-for=60s"
#   command: ['sh', '-c', 'echo "The app is running NOWA !"; cp -R /bzt-configs-mount /bzt-configs; bzt -l /tmp/artifacts/bzt.log']
#    args:
#    - "-report"
#   - TestRunD.yml
#    - CSR_1.jmx
#    - "--option=execution.0.concurrency=2"
#    - "--option=execution.0.hold-for=60s"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    volumeMounts:
      - name: perf-config
        mountPath: /bzt-configs-mount
      - name: test-data
        mountPath: /bzt-configs/data
      - name: test-artifacts
        mountPath: /bzt-configs/TestArtifacts
      - name: kube-api-access-4x7vn
        mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  volumes:
    - name: perf-config
      configMap:
        name: ags-performance-testing-broker
    - name: test-data
      emptyDir: {}
    - name: test-artifacts
      emptyDir: {}
    - name: kube-api-access-4x7vn
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
