apiVersion: v1
kind: Pod
metadata:
  name: perf-taurus-pod-combined-all
  namespace: ags-qa
spec:
  restartPolicy: Never
  containers:
  - name: perf-taurus-container-user
    image: blazemeter/taurus:1.16.32
    command: ["/bin/sh"]
    args:
    - "-c"
    - "cp /bzt-configs-mount/TestRunUser.yml /bzt-configs-mount/userProfile.jmx /bzt-configs-mount/tf_member_login.jmx /bzt-configs-mount/tf_member_logout.jmx /bzt-configs-mount/tf_account_overview.jmx /bzt-configs-mount/member_login.csv /bzt-configs/; ls /bzt-configs; pwd; bzt -l /tmp/artifacts/bzt.log -report TestRunUser.yml userProfile.jmx"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    volumeMounts:
      - name: perf-config-user
        mountPath: /bzt-configs-mount
      - name: test-data
        mountPath: /bzt-configs/data
      - name: test-artifacts
        mountPath: /bzt-configs/TestArtifacts
      - name: kube-api-access-4x7vn
        mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  - name: perf-taurus-container-csr
    image: blazemeter/taurus:1.16.32
    command: ["/bin/sh"]
    args:
    - "-c"
    - "cp /bzt-configs-mount/TestRunCSR.yml /bzt-configs-mount/csr_search.jmx /bzt-configs-mount/csr_login.csv /bzt-configs-mount/csr_acct_search.csv /bzt-configs/; ls /bzt-configs; pwd; bzt -l /tmp/artifacts/bzt.log -report TestRunCSR.yml csr_search.jmx"
    #   command: ['sh', '-c', 'echo "The app is running NOWA !"; cp -R /bzt-configs-mount /bzt-configs; bzt -l /tmp/artifacts/bzt.log']
#    args:
#    - "-report"
#   - TestRunD.yml
#    - CSR_1.jmx
#    - "--option=execution.0.concurrency=2"
#    - "--option=execution.0.hold-for=60s"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    volumeMounts:
      - name: perf-config-csr
        mountPath: /bzt-configs-mount
      - name: test-data
        mountPath: /bzt-configs/data
      - name: test-artifacts
        mountPath: /bzt-configs/TestArtifacts
      - name: kube-api-access-4x7vn
        mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  - name: perf-taurus-container-broker
    image: blazemeter/taurus:1.16.32
    command: ["/bin/sh"]
    args:
    - "-c"
    - "cp /bzt-configs-mount/TestRunBroker.yml /bzt-configs-mount/broker.jmx /bzt-configs-mount/broker.csv  /bzt-configs/; ls /bzt-configs; pwd; bzt TestRunBroker.yml broker.jmx"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    volumeMounts:
      - name: perf-config-broker
        mountPath: /bzt-configs-mount
      - name: test-data
        mountPath: /bzt-configs/data
      - name: test-artifacts
        mountPath: /bzt-configs/TestArtifacts
      - name: kube-api-access-4x7vn
        mountPath: /var/run/secrets/kubernetes.io/serviceaccount
  volumes:
    - name: perf-config-user
      configMap:
        name: ags-performance-testing-user
    - name: perf-config-broker
      configMap:
        name: ags-performance-testing-broker
    - name: perf-config-csr
      configMap:
        name: ags-performance-testing-csr
    - name: test-data
      emptyDir: {}
    - name: test-artifacts
      emptyDir: {}
    - name: kube-api-access-4x7vn
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
