apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-taurus-deployment-user
  namespace: ags-qa
spec:
  selector:
    matchLabels:
      app: perf-taurus-deployment-user
  replicas: 1 # tells deployment to run 6 pods matching the template
  template:
    metadata:
      labels:
        app: perf-taurus-deployment-user
    spec:
      restartPolicy: Always
      volumes:
          - name: perf-config
            configMap:
              name: ags-performance-testing-user
          - name: test-data
            emptyDir: {}
          - name: test-artifacts
            emptyDir: {}
          - name: kube-api-access-4x7vn
            projected:
              defaultMode: 420
              sources:
                - serviceAccountToken:
                    expirationSeconds: 3607
                    path: token
                - configMap:
                    items:
                      - key: ca.crt
                        path: ca.crt
                    name: kube-root-ca.crt
                - downwardAPI:
                    items:
                      - fieldRef:
                          apiVersion: v1
                          fieldPath: metadata.namespace
                        path: namespace
      containers:
      - name: perf-taurus-pod-user
        image: blazemeter/taurus:1.16.32
        command: ["/bin/sh"]
        args:
          - "-c"
          - "cp /bzt-configs-mount/TestRunUser.yml /bzt-configs-mount/userProfile.jmx /bzt-configs-mount/tf_member_login.jmx /bzt-configs-mount/tf_member_logout.jmx /bzt-configs-mount/tf_account_overview.jmx /bzt-configs-mount/member_login.csv /bzt-configs/; ls /bzt-configs; pwd; bzt -l /tmp/artifacts/bzt.log -report TestRunUser.yml userProfile.jmx"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
            - name: perf-config
              mountPath: /bzt-configs-mount
            - name: test-data
              mountPath: /bzt-configs/data
            - name: test-artifacts
              mountPath: /bzt-configs/TestArtifacts
            - name: kube-api-access-4x7vn
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount        