jenv=stage1
jkeyfile=secretKeyStage.txt
jauthentication=agsup-auth-server-stage1.gs.ascensus.com
jauthenticationui=agsup-auth-ui-stage1.gs.ascensus.com
jconfidentialclientid=11A5F1ECF3CB47A1AC20B228DC8A468E
jconfidentialclientsecret=tCSODjP0cNMZJgaew0wuunkLdNUlATxgphZBCZ2UzXO7yLSh7OSE6jc8xIUaQ2MR
jclientid=9D117E3DBAE24746BA3B2EEE85C7472C
jusername=/QPUJb4Y3PSbDQn9Q9RgCi7dGkZmqHauJos5jVMs7oY=
jpassword=xKk2GydTAJk8LCTCGdnpwoyJnMzYxt2aFSolFlclYfQ=
jmetadatahost=agsup-metadata-web-stage1.gs.ascensus.com
jaccounthost=agsup-aws-account-web-stage1.gs.ascensus.com
jfinancialhost=agsup-aws-financial-web-stage1.gs.ascensus.com
jenrollmenthost=agsup-ui-enrollment-stage1.gs.ascensus.com
